language: python
python:
  - "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt"

# command to run tests
script: python test/test.py TestLambda

# zip lambda
before_deploy:
  - zip lambda_function -r project/*
  - mkdir upload
  - mv lambda_function.zip upload/lambda_function.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  region: eu-central-1
  skip_cleanup: true
  upload-dir: travis-builds
  local_dir: upload
